### ISSUE TITLE
lower-threshold of iron-scroll-threshold fires everytime I scroll

### ISSUE THREAD

**Issue by ziszo** [PolymerElements/iron-scroll-threshold#11]
### polymer-cli v0.13.0

lower-threshold fires everytime I scroll.

```
<iron-scroll-threshold id="scrollThreshold"
        scroll-target="document"
        lower-threshold="500"
        on-lower-threshold="loadMoreData">
      </iron-scroll-threshold>
```

script:

```
            loadMoreData: function(e) {
                console.log('load more');
                this.$.scrollThreshold.clearTriggers();
            }
```

**Comment by blasten** [comment]
Did it reach the end of the scrollable content? If yes, that's the expected behavior.

**Comment by ziszo** [comment]
It fires even if I scroll a bit, not reaching the bottom.

**Comment by minhlong139** [comment]
I think the problem is the first time iron-list has 0px ~ is reaching the bottom so iron-scroll-threshold raise lower event. See attachment: demo has the same problem

<img width="941" alt="screen shot 2016-08-08 at 21 15 16" src="https://cloud.githubusercontent.com/assets/171335/17482723/4780118e-5dad-11e6-87ca-5d8a65d3d416.png">

**Comment by blasten** [comment]
This issue was moved to PolymerElements/iron-list#290
